services:
  - type: web
    name: ig-bot-service
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y \
        libsoup-3.0-0 \
        libgstgl1.0-0 \
        libgstreamer-plugins-bad1.0-0 \
        libenchant-2-2 \
        libsecret-1-0 \
        libmanette-0.2-0 \
        libgles2 \
        libgtk-3-0 \
        libxcomposite1 \
        libxdamage1 \
        libxrandr2 \
        libasound2 \
        libnss3 \
        libxss1 \
        libxtst6 \
        fonts-liberation \
        libdrm2 \
        libgbm1 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libcups2 \
        libpango-1.0-0 \
        libxshmfence1 \
        libnspr4 && \
      python --version && \
      pip install -r requirements.txt && \
      playwright install
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: IG_USERNAME
        value: jasim_as
      - key: IG_PASSWORD
        value: movieforyou
