services:
  - type: web
    name: ig-bot-service
    env: python
    plan: free
    buildCommand: |
      python --version
      pip install -r requirements.txt
      playwright install
    startCommand: gunicorn server:app -w 1 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: IG_USERNAME
        value: jasim_as
      - key: IG_PASSWORD
        value: movieforyou
      - key: 
        value: jasim_as
      - key: IG_PASSWORD
        value: movieforyou
