
services:
  - type: web
    name: ig-bot-service
    env: python
    plan: free
    buildCommand: |
      python --version
      pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: IG_USERNAME
        value: jasim_as
      - key: IG_PASSWORD
        value: movieforyou
